### ISSUE TITLE
this repo can help you 

### ISSUE THREAD

**Issue by mohsenuss91** [forabi/arabic-tech-terminology#1]
https://github.com/01walid/Nibras

**Comment by forabi** [comment]
شكرًا سألقي نظرة عليه

**Comment by forabi** [comment]
المصطلحات التي نرغب بترجمتها تختلف كليًا عمّا يحويه البرنامج. نرغب بإنشاء مرجع معتمد للمصطلحات المتعلقة مباشرةً بعلوم الحاسوب وهندسة البرمجيّات.
